export const MATCH_CREATED           = '@match/CREATE'
export const MATCH_CREATED_SUCCESS   = '@match/CREATE_SUCCESS'
export const MATCH_CREATED_ERROR     = '@match/CREATE_ERROR'
export const MATCHES_REQUESTED       = '@matches/REQUESTED'
export const MATCHES_REQUESTED_SUCCESS = '@matches/REQUESTED_SUCCESS'
export const MATCHES_REQUESTED_ERROR = '@matches/REQUESTED_ERROR'
